language: node_js
node_js:
  - "7.4"
before_script:
  - tsc -p tsconfig.json
  - tsc -p tests/tsconfig.json
after_script:
  - npm run coveralls
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8