export declare const STARTING: string;
export declare const STARTED: string;
export declare const FAILED: string;
export declare const DOWNLOADING_BINARY: string;
export declare const BINARY_CORRUPTED: string;
export declare const STOPPING: string;
export declare const STOPPED: string;
export declare const ERROR: string;
export declare const TIME_NOT_SYNCED: string;
export declare const FATAL: string;
export declare const IPC_CONNECTED: string;
export declare const IPC_DISCONNECTED: string;
export declare const ETH_NODE_OK: string;
export declare const TX_MINED: string;
export declare const UPDATING_BINARY: string;
export declare const START_OPTIONS: {
    cache: number;
    fast: string;
};
export declare const BIN_PATH: string;
export declare const START_FILTER: string;
export declare const INFO_FILTER: string;
