"use strict";
exports.STARTING = 'GETH_STARTING';
exports.STARTED = 'GETH_STARTED';
exports.FAILED = 'GETH_START_FAILED';
exports.DOWNLOADING_BINARY = 'GETH_DOWNLOADING_BINARY';
exports.BINARY_CORRUPTED = 'GETH_BINARY_CORRUPTED';
exports.STOPPING = 'GETH_STOPPING';
exports.STOPPED = 'GETH_STOPPED';
exports.ERROR = 'GETH_ERROR';
exports.TIME_NOT_SYNCED = 'GETH_TIME_NOT_SYNCED';
exports.START_OPTIONS = { cache: 512, shh: '', fast: '', testnet: '' };
exports.ETH_NETWORK_ID = '2';
